### ISSUE TITLE
传图片的时候失败

### ISSUE THREAD

**Issue by qq326646683** [easemob/webim-react-native#13]
message.js:
    var _complete = function (data) {
      console.log(data);//
![2017-03-02 10 20 44](https://cloud.githubusercontent.com/assets/15717688/23510968/8e091eda-ff96-11e6-84d0-e465f0166d5f.png)

MessageRedux.js:
                onFileUploadError: function (error) {
                    console.log(error)
                    dispatch(Creators.updateMessageStatus(pMessage, 'fail'))
                },//
![2017-03-02 10 22 29](https://cloud.githubusercontent.com/assets/15717688/23511024/c307f980-ff96-11e6-9812-eaa34cb8e7d9.png)

**Comment by as278257357** [comment]
回调写的不对

**Comment by qq326646683** [comment]
onFileUploadError: function (error) {
                    console.log(error)
                    dispatch(Creators.updateMessageStatus(pMessage, 'fail'))
                },
                onFileUploadComplete: function (data) {
                    console.log(data)
                    url = data.uri + '/' + data.entities[0].uuid;
                    dispatch(Creators.updateMessageStatus(pMessage, 'sent'))
                },
                success: function (id) {
                    console.log(id)
                },

**Comment by qq326646683** [comment]
我是复制demo中的MessageRedux.js的内容，哪里有错呢 @as278257357

**Comment by wytheme** [comment]
@qq326646683 , 环信后台的api限制了特殊字符会导致上传失败

见changelog: 此版本由于升级了react native库，需要先 npm install 安装依赖包 2. 去工程Librares中找到： RCTNetwork.xcodeproj / RCTNetworking.mm / RCTGenerateFormBoundary -> 去掉特殊字符 / . 等
