### ISSUE TITLE
demo程序无法npm install

### ISSUE THREAD

**Issue by evanywang** [easemob/webim-react-native#33]
知道情况吗？
make: *** [install] Error 1
npm WARN react-native@0.39.2 requires a peer of react@~15.4.0-rc.4 but none was installed.
npm WARN reactotron-react-native@1.12.1 requires a peer of react-native@>=0.40.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! linter@0.0.7 install: `make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the linter@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by panhs** [comment]
ME TOO

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/xx/.nvm/versions/node/v8.0.0/bin/node" "/Users/xx/.nvm/versions/node/v8.0.0/bin/npm" "install"
npm ERR! node v8.0.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! linter@0.0.7 install: `make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the linter@0.0.7 install script 'make install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs linter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls linter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xx/Documents/Github_projects/webim-react-native/npm-debug.log
panheshundeMacBook-Pro:webim-react-native xx$ react-native run-android

**Comment by panhs** [comment]
忽略以后继续部署的话 会提示strict mode does not allow function declarations in a lexical，然后修改.\node_modules\react-native\Libraries\Core\InitializeCore.js 112行，改完还是不行

**Comment by wytheme** [comment]
尝试一下  ： https://github.com/facebook/react-native/issues/11389#issuecomment-265995961

**Comment by panhs** [comment]
试了没用

**Comment by wytheme** [comment]
@panhs , 
提供一下你做了哪些尝试，每次尝试后的结果是什么样的
尝试重新部署项目并重现以上问题，并提供重现步骤

**Comment by V1sk** [comment]
遇到了相同的问题：
`chenjianweideMacBook-Pro:webim-react-native chenjianwei$ npm install

> linter@0.0.7 install /Users/chenjianwei/RN_Demo/webim-react-native/node_modules/linter
> make install

cd ./deps/closure-linter && python ./setup.py install 
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-3363.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

make: *** [install] Error 1
npm WARN react-native@0.39.2 requires a peer of react@~15.4.0-rc.4 but none is installed. You must install peer dependencies yourself.
npm WARN reactotron-react-native@1.12.3 requires a peer of react-native@>=0.40.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! linter@0.0.7 install: `make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the linter@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chenjianwei/.npm/_logs/2017-10-31T10_11_18_543Z-debug.log
chenjianweideMacBook-Pro:webim-react-native chenjianwei$ `

**Comment by misakichan** [comment]
同报错。rn版本太老了。。。
