### ISSUE TITLE
Image Not Render with Url

### ISSUE THREAD

**Issue by movier** [easemob/webim-react-native#37]
When other people sent me a image, I can get the url of the image with format like this: 
```
https://a1.easemob.com/OrgName/AppName/chatfiles/58428910-b005-11e7-b5b3-9324bb6f1d17
```

But when render the image with code:
https://github.com/easemob/webim-react-native/blob/47e055514b239b590a21cece2b637a0c7f8d0c55/App/Containers/MessageScreen.js#L374-L375

it just not work. 

Environment:
React Native version: 0.48.4

I wonder whether other people encounter the same problem or am I doing something wrong. Thank you very much.

**Comment by yazhengwang** [comment]
+1 @movier Did you fix it?

**Comment by movier** [comment]
@yazhengwang Not yet. I'm afraid this repository is no longer maintained anymore. We have to fix the problem by ourself. I will inform you as soon as I fix it. Good luck!

**Comment by yazhengwang** [comment]
@movier I fix it

**Comment by movier** [comment]
@yazhengwang Congratulation! If possible please create a PR. Thanks.

**Comment by yazhengwang** [comment]
I switched to a selection of components  react-native-image-picker,you can have a try @movier
