### ISSUE TITLE
ios启动错误，是为什么呢

### ISSUE THREAD

**Issue by qq573725206** [easemob/webim-react-native#6]
/Applications/MAMP/htdocs/int/webim-react-native/node_modules/react-native-maps/ios/AirMaps/Callout/SMCalloutView.h:43:36: Cannot find protocol declaration for 'CAAnimationDelegate'; did you mean 'UIApplicationDelegate'?

**Comment by wytheme** [comment]
see: https://github.com/airbnb/react-native-maps/issues/703
