### ISSUE TITLE
为什么iOS只能支持到9.0版本？react native本身是可以支持到7.0的吧？

### ISSUE THREAD

**Issue by stephenlyu** [easemob/webim-react-native#8]

**Comment by wytheme** [comment]
react-native Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0

考虑到占有率，并没有调试 8.0 相关的系统，目前以完善功能为主。

**Comment by stephenlv** [comment]
我已经在8.3系统上运行成功了，谢谢~

**Comment by daffy6537** [comment]
@wytheme 8.0+的人还是很多的

**Comment by daffy6537** [comment]
@wytheme 起项目以后 报Cannot read property 'style' of undefined   好像是和 Scene.js文件有关
