### ISSUE TITLE
我集成了webim-react-native用于做客服，请问怎么样发送track，order和vistor信息呢？

### ISSUE THREAD

**Issue by stephenlv** [easemob/webim-react-native#9]

**Comment by wytheme** [comment]
这个仅仅是集成了IM的SDK，客服方面的并没有集成

IM的api我没有记得有何处涉及 `track，order和vistor` 信息，需要你先确认下，这是否是IM的功能

**Comment by stephenlv** [comment]
你们的客服系统不是基于IM的么？我现在集成了webim-react-native，并且可以与客服后台进行互发消息，只是需要发送订单，或者商品之类的信息，不知道该怎么做？我看了iOS的集成，就是在消息体的ext中加入特定的信息，就可以实现发送订单，商品之类信息的功能？

如果可以，请帮忙在环信内部咨询一下，谢谢！

**Comment by wytheme** [comment]
你还可以按照这个逻辑处理，通过ext自定义消息，IM是支持的，见MessageRedux.js
